apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster
  namespace: argocd
spec:
  generators:
    - clusters: {}
  template:
    metadata:
      name: 'appset-cluster-{{name}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/any2names/argocd-example-apps-any2names
        targetRevision: HEAD
        path: lightweight/app-a
      destination:
        server: '{{server}}'
        namespace: 'appset-cluster-{{name}}'
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          prune: true
          selfHeal: true
